### ISSUE TITLE
Installation of 0.0.5 causes an Error

### ISSUE THREAD

**Issue by Harald-B-Rupp** [iobroker-community-adapters/ioBroker.snips#2]
During the installation of Version 0.0.5 i get an Error, the Adapter will not get installed correnctly.

`Fertig mit Fehler: module.js:674 throw err; ^ SyntaxError: /opt/iobroker/node_modules/iobroker.snips/io-package.json: Unexpected string in JSON at position 396 at JSON.parse () at Object.Module._extensions..json (module.js:671:27) at Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:219:23) at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:748:44 at Timeout.upload [as _onTimeout] (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:287:57)`

**Comment by Bettman66** [comment]
I forgot a comma, please reload.
