### ISSUE TITLE
Richtige Erkennung von Snips wird falsch korrigiert

### ISSUE THREAD

**Issue by Pittini** [iobroker-community-adapters/ioBroker.snips#29]
Vielleicht versteh ich ja nur was nicht, aber das sieht mir nach Bug aus. Wenn nicht wärs toll wenn mir einer sagen könnte warum Luftfeuchtigkeit nicht akzeptiert wird. Das gleiche Spiel mit "Temperatur" funktioniert übrigens.
![Inked2020-01-04 15_48_12-objects - ioBroker_LI](https://user-images.githubusercontent.com/51408942/71767212-31ce3f00-2f0a-11ea-9fe7-7fffebf93e84.jpg)

**Comment by unltdnetworx** [comment]
Das liegt daran, dass die Luftfeuchtigkeit im dem Slot Wetter asoziert wurde. Hab ich behoben. Bitte einfach den Assistenten Updaten.

**Comment by Pittini** [comment]
> einfach den Assistenten Updaten.

Hab ich gemacht, aber außer dass jetzt meine injekteten Wörter weg sind kommt immer noch "Wetter" statt Luftfeuchtigkeit.
Da SNIPS ja ab Ende Jan nicht mehr upgedatet werden kann, weiö die Console dann weg ist, möchte ich das vorher noch einigermaßen zum laufen bringen. Ich schreib grad mein eigenes Auswertescript, also ohne Text2Command Adapter. WEnn da jetzt Sachen korrigiert werden, also nicht das in die Slots reinkommt was gesprochen wurde, hab ich ein Problem, weil dann bräuchte ich von Dir ne Ersetzungsliste welches Wort wofür ausgegeben wird. Hoffe Du verstehst was ich mein.

**Comment by unltdnetworx** [comment]
Dass die Wörter weg sind, wurde bereits im Forum erklärt. Und ein Möglichkeit genannt, wie man diese quasi sichern kann oder eben an mich melden, damit ich sie global eintragen kann. Sry, dafür.

Bei deinem Update ist dann aber etwas schief gegangen. Sowohl in der Console von Snips, als auch auf meinem Assistenen funktioniert es einwandfrei. Probier es doch mal unter console.snips.ai aus.

`{
  "input": "wie ist die luftfeuchtigkeit im wohnzimmer",
  "intent": {
    "intentName": "unltdnetworx:getStatusDE",
    "confidenceScore": 0.9114349
  },
  "slots": [
    {
      "rawValue": "luftfeuchtigkeit",
      "value": {
        "kind": "Custom",
        "value": "Luftfeuchtigkeit"
      },
      "range": {
        "start": 12,
        "end": 28
      },
      "entity": "de.iobroker.unit",
      "slotName": "status"
    },
    {
      "rawValue": "wohnzimmer",
      "value": {
        "kind": "Custom",
        "value": "Wohnzimmer"
      },
      "range": {
        "start": 32,
        "end": 42
      },
      "entity": "de.iobroker.room",
      "slotName": "room"
    }
  ]
}`

**Comment by Pittini** [comment]
Screenshot gerade eben gemacht, sieht bei mir anders aus.
![2020-01-04 21_57_18-](https://user-images.githubusercontent.com/51408942/71771564-745d3f00-2f3d-11ea-9f6c-1a1548e8ec58.png)

**Comment by Pittini** [comment]
Ich hab jetzt:
Den Asisstenten gelöscht und neu gemacht - keine Änderung
SNIPS komplett neugestartet nach Assi install - keine Änderung
Iob neu gestartet - keine Änderung

Wär dankbar für Tipps/Hilfe.

**Comment by unltdnetworx** [comment]
Lösche und installiere den Assistenten nochmal neu. Jetzt sollte es gehen. Hab mir extra einen neuen Account angelegt und etwas geändert. Funktioniert jetzt.

**Comment by Pittini** [comment]
Jap, jetzt klappt das. Vielen Dank für Deine Zeit. 
Nur Interessehalber, wie verfährst Du wenn Snips nicht mehr zugänglich ist? Haste schon Ersatz gefunden?

**Comment by unltdnetworx** [comment]
Ich experimentiere gerade mit Almond von der Stanford Universität. Mal sehen, ob das für mich geeignet ist.

**Comment by capitaenz** [comment]
@unltdnetworx 
Ich erhalte Snips grad auch nur noch so am Leben und suche eine Alternative.
Bist du mit Almond schon weitergekommen?

VG
Leif

**Comment by unltdnetworx** [comment]
Leider nicht, bzw. läuft es nur auf Englisch. Daher probiere ich gerade deutsche Sprachsynthese mit Python und Tacotron, dann in Verbindung mit eigenem Sprachassistenten. Mal sehen, was das wird.
