### ISSUE TITLE
purge snips 

### ISSUE THREAD

**Issue by MathiasJZ** [iobroker-community-adapters/ioBroker.snips#30]
A question in advance:
Snips is bought from Sonos.
Google will buy Sonos.
The free gui is ending at first of february.
It's possible to remove snips from your adapter list default and lastest.
I'm worry snips won't work from first february and new operator want to install it.
Greetings,
Mathias

**Comment by Pittini** [comment]
If Snips really work no more after The first of february > ok. But i think, its still working, but its impossible to change anything or get updates. If this is the behaivior, please let the Adapter stay.

**Comment by unltdnetworx** [comment]
The sale of the project is correct, but I think the functionality is still guaranteed. I my opinion it's better to keep it in the repository. Will write a hint into the readme.
