### ISSUE TITLE
Update stable version in repo from 1.5.0 to 1.5.1

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.snips#36]
# Think about update stable version to 1.5.1
**Version**: stable=**1.5.0** (355 days old) => latest=**1.5.1** (15 days old)
**Installs**: stable=**175** (82.55%), latest=**17** (8.02%), total=**212**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1303)

**Comment by unltdnetworx** [comment]
Pull into stable requested.
