### ISSUE TITLE
Update stable version in repo from 1.5.0 to 1.5.1

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.snips#38]
# Think about update stable version to 1.5.1
**Version**: stable=**1.5.0** (357 days old) => latest=**1.5.1** (17 days old)
**Installs**: stable=**175** (82.94%), latest=**18** (8.53%), total=**211**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L1303)

**Comment by unltdnetworx** [comment]
Done
